# Docker Compose configuration for development
version: "3.9" 

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose port 3000 for the backend
    volumes:
      - ./Backend:/app # Mount the local code into the container
      - backend_node_modules:/app/node_modules # Named volume for dependencies
    environment:
      - NODE_ENV=development # Set the environment to development
    command: yarn dev # Command to start the backend in development mode

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Expose port 5173 for the frontend (Vite)
    volumes:
      - ./Frontend:/app # Mount the local code into the container
      - frontend_node_modules:/app/node_modules # Named volume for dependencies
    environment:
      - NODE_ENV=development # Set the environment to development
    command: npm run dev # Command to start the frontend in development mode

volumes:
  backend_node_modules: # Volume for the backend
  frontend_node_modules: # Volume for the frontend


# # Docker Compose configuration for production
# version: "3.9" 

# services:
#   backend:
#     build:
#       context: ./Backend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000" # Map port 3000 on the host to port 3000 in the container for the backend
#     environment:
#       - NODE_ENV=production # Set the environment to production
#     command: yarn start # Command to start the backend in production mode

#   frontend:
#     build:
#       context: ./Frontend
#       dockerfile: Dockerfile
#       target: production
#     ports:
#       - "80:80" # Map port 80 on the host to port 80 in the container for the frontend (NGINX)
#     environment:
#       - NODE_ENV=production # Set the environment to production